# JDBC 逻辑库名称。在集群模式中，使用该参数来联通 ShardingSphere-JDBC 与 ShardingSphere-Proxy。
# 默认值：logic_db
#打印SQL
props:
  sql-show: true
#为方便调试，暂时使用Standalone模式
mode:
  type: Standalone
  repository:
    type: JDBC

dataSources:
  ds_0_write:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/testsharding1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 30000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
  ds_0_read:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/testsharding1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 30000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
  ds_1_write:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/testsharding2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 30000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
  ds_1_read:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/testsharding2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 10
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 30000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL

rules:
  - !READWRITE_SPLITTING
      dataSources:
        readwrite_ds_0:
          staticStrategy:
            writeDataSourceName: ds_0_write
            readDataSourceNames:
              - ds_0_read
          loadBalancerName: round_robin
        readwrite_ds_1:
          staticStrategy:
            writeDataSourceName: ds_1_write
            readDataSourceNames:
              - ds_1_read
          loadBalancerName: round_robin
      loadBalancers:
        round_robin:
          type: ROUND_ROBIN
  - !TRANSACTION
    defaultType: LOCAL
#    defaultType: XA
#    providerType: Narayana/Atomikos
#    defaultType: BASE
#    providerType: Seata

  - !SHARDING
    tables:
      t_user:
        actualDataNodes: readwrite_ds_0.t_user_${1..2}


    #默认的数据库分片策略
#    defaultDatabaseStrategy:
#      hint:
#        shardingAlgorithmName: my-hint
    defaultTableStrategy:
      standard:
        shardingColumn: id
        shardingAlgorithmName: my-standard
#    bindingTables:
#      - t_user
#
#    broadcastTables:
#      - t_user
    #分片算法
    shardingAlgorithms:
      my-standard:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.example.demo.sharding.CustomShardingStandardAlgorithm

    #自定义的SQL审计策略
#    defaultAuditStrategy:
#      auditorNames:
#        - sharding_key_required_auditor
#    auditors:
#      sharding_key_required_auditor:
#        type: CUSTOM_SHARDING_CONDITIONS

